multiple
~~~~~~~~

**tip**: ``Boolean`` **varsayılan**: ``false``

Eğer true yapılırsa kullanıcı select üzerinden çoklu seçimler yapabilir 
(bu tek bir seçim yapmanın tam tersidir). Bu kısım ``expanded`` seçeneğinin
aldığı değere göre ekrana select etiketi ile oluşturulmuş bir liste ya da 
checkbox'lardan oluşturulmuş bir liste basacaktır. 
Expanded true durumunda bu eğer true ise checkbox'lardan oluşan bir liste
false ise radio butonlardan oluşan bir liste ekrana basılacaktır. Dönüş
değeri ise array olacaktır.
