required
~~~~~~~~

**tip**: ``Boolean`` **varsayılan**: ``true``

Eğer true ise bir `HTML5 required attribute`_ ekrana basılacaktır.
İlgili form alanı ``etiketi`` aynı zamanda bir ``required`` css sitili 
ile de ekrana basılır.

Bu yöntem yüzeysel ve bağımsız bir form doğrulama şeklidir. En iyisi
Symfony'nin form alan tipini tahmin etmesine izin vererek bu seçeneğin
değerini sizin veri doğrulama bilginizden kullanmasını sağlamaktır.

.. _`HTML5 required attribute`: http://diveintohtml5.info/forms.html
