Select etiketi, Checkbox'lar ya da Radio Butonları
--------------------------------------------------

Bu alan ``expanded`` ve ``multiple`` seçeneklerine bağlı olarak
farklı HTML elementlerini ekrana basar:

+-------------------------------------------+----------+----------+
| element tipi                              | expanded | multiple |
+===========================================+==========+==========+
| select etiketi                            | false    | false    |
+-------------------------------------------+----------+----------+
| select etiketi (``multiple`` niteliğiyle) | false    | true     |
+-------------------------------------------+----------+----------+
| radio butonları                           | true     | false    |
+-------------------------------------------+----------+----------+
| checkbox'lar                              | true     | true     |
+-------------------------------------------+----------+----------+
