* **Konfigürasyon Seçenekleri**

  Hiç merak ettiniz mi uygulamanızda ``app/config/config.yml`` şeklinde 
  bulunan dosyaların içerisinde neler var ?. Bu bölümde konfigürasyon
  dosyasındaki (Örn: ``app/config/config.yml``) anahtarlar altında belirlenmiş  
  mevcut tüm konfigürasyon ayarları açıklanacaktır.
  
  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **Formlar ve Doğrulama**

  * :doc:`Form Field Type Reference</reference/forms/types>`
  * :doc:`Validation Constraints Reference </reference/constraints>`
  * :doc:`Twig Template Function Reference</reference/forms/twig_reference>`

* **Diğer Alanlar**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
