* **Konfigürasyon Seçenekleri**

  Hiç merak ettiniz mi acaba uygulamanız içerisinde ``app/config/config.yml`` 
  şeklinde bulunan dosyaların içerisinde neler var ?. Bu bölümde konfigürasyon
  dosyasındaki (Örn: ``app/config/config.yml``) bazı anahtarlar altında belirlenmiş  
  mevcut konfigürasyon ayarlarının tümü açıklanacaktır.
  
  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **Formlar ve Doğrulama**

  * :doc:`Form Alan Tipleri Referansı</reference/forms/types>`
  * :doc:`Veri Doğrulama Koşutları Referansı </reference/constraints>`
  * :doc:`Twig Şablon Fonksiyonları Referansı</reference/forms/twig_reference>`

* **Diğer Alanlar**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
