Metin(Text) Alanları
~~~~~~~~~~~~~~~~~~~~

* :doc:`metin(text)</reference/forms/types/text>`
* :doc:`metin alanı(textarea)</reference/forms/types/textarea>`
* :doc:`e-posta</reference/forms/types/email>`
* :doc:`sayı(integer)</reference/forms/types/integer>`
* :doc:`para</reference/forms/types/money>`
* :doc:`rakam</reference/forms/types/number>`
* :doc:`parola</reference/forms/types/password>`
* :doc:`yüzdelik</reference/forms/types/percent>`
* :doc:`arama</reference/forms/types/search>`
* :doc:`url</reference/forms/types/url>`

Seçim Alanları
~~~~~~~~~~~~~~

* :doc:`seçim listesi</reference/forms/types/choice>`
* :doc:`veritabanından seçim listesi(entity)</reference/forms/types/entity>`
* :doc:`ülke</reference/forms/types/country>`
* :doc:`dil</reference/forms/types/language>`
* :doc:`yerel</reference/forms/types/locale>`
* :doc:`saatkuşağı(timezone)</reference/forms/types/timezone>`

Tarih ve Zaman Alanları
~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`tarih</reference/forms/types/date>`
* :doc:`tarih ve saat (datetime)</reference/forms/types/datetime>`
* :doc:`saat</reference/forms/types/time>`
* :doc:`doğum günü</reference/forms/types/birthday>`

Diğer Alanlar
~~~~~~~~~~~~~

* :doc:`checkbox</reference/forms/types/checkbox>`
* :doc:`dosya</reference/forms/types/file>`
* :doc:`radio</reference/forms/types/radio>`

Alan Gurupları
~~~~~~~~~~~~~~

* :doc:`kolleksiyon</reference/forms/types/collection>`
* :doc:`tekrarlı (repeated)</reference/forms/types/repeated>`

Gizli Alanlar
~~~~~~~~~~~~~

* :doc:`hidden</reference/forms/types/hidden>`
* :doc:`csrf</reference/forms/types/csrf>`

Temel Alanlar
~~~~~~~~~~~~~

* :doc:`alan(field)</reference/forms/types/field>`
* :doc:`form</reference/forms/types/form>`
