Temel Kısıtlar
~~~~~~~~~~~~~~~~~

Bunları kullanarak en temel kısıtları nesnenizin sınıf değişkenlerine
ya da dönüş değerlerine uygulayabilirsiniz.

* :doc:`NotBlank </reference/constraints/NotBlank>`
* :doc:`Blank </reference/constraints/Blank>`
* :doc:`NotNull </reference/constraints/NotNull>`
* :doc:`Null </reference/constraints/Null>`
* :doc:`True </reference/constraints/True>`
* :doc:`False </reference/constraints/False>`
* :doc:`Type </reference/constraints/Type>`

Metin Kısıtları
~~~~~~~~~~~~~~~

* :doc:`Email </reference/constraints/Email>`
* :doc:`MinLength </reference/constraints/MinLength>`
* :doc:`MaxLength </reference/constraints/MaxLength>`
* :doc:`Url </reference/constraints/Url>`
* :doc:`Regex </reference/constraints/Regex>`
* :doc:`Ip </reference/constraints/Ip>`

Sayı Kısıtları
~~~~~~~~~~~~~~

* :doc:`Max </reference/constraints/Max>`
* :doc:`Min </reference/constraints/Min>`

Tarih Kısıtları
~~~~~~~~~~~~~~~

* :doc:`Date </reference/constraints/Date>`
* :doc:`DateTime </reference/constraints/DateTime>`
* :doc:`Time </reference/constraints/Time>`

Kolleksiyon Kısıtları
~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Choice </reference/constraints/Choice>`
* :doc:`Collection </reference/constraints/Collection>`
* :doc:`UniqueEntity </reference/constraints/UniqueEntity>`
* :doc:`Language </reference/constraints/Language>`
* :doc:`Locale </reference/constraints/Locale>`
* :doc:`Country </reference/constraints/Country>`

Dosya ısıtları
~~~~~~~~~~~~~~

* :doc:`File </reference/constraints/File>`
* :doc:`Image </reference/constraints/Image>`

Diğer Kısıtlar
~~~~~~~~~~~~~~

* :doc:`Callback </reference/constraints/Callback>`
* :doc:`All </reference/constraints/All>`
* :doc:`Valid </reference/constraints/Valid>`
