* **Code**

  * :doc:`Hatalar </contributing/code/bugs>`
  * :doc:`Yamalar </contributing/code/patches>`
  * :doc:`Güvenlik </contributing/code/security>`
  * :doc:`Testler </contributing/code/tests>`
  * :doc:`Kodlama Standartları</contributing/code/standards>`
  * :doc:`Kodlama Düzeleri</contributing/code/conventions>`
  * :doc:`Lisans </contributing/code/license>`

* **Documentation**

  * :doc:`Genel Bakış </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Çeviriler </contributing/documentation/translations>`
  * :doc:`Lisans </contributing/documentation/license>`

* **Community**

  * :doc:`IRC Toplantıları </contributing/community/irc>`
  * :doc:`Diğer Kaynaklar </contributing/community/other>`
